import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { getAll, search, update } from '../API/booksAPI'
import { book } from '../components/Book/Book.component'
import { RootState } from './store'

export interface bookState {
    value: book[]
    searchBooks: book[]
    loading: boolean
    error: boolean
}

const initialState: bookState = {
    value: [],
    searchBooks: [],
    loading: false,
    error: false
}

export const getAllBooks = createAsyncThunk('book/getAllBooks', async () => {
    const response = await getAll()
    // The value we return becomes the `fulfilled` action payload
    return response
})

export const updateBook = createAsyncThunk('book/updateBook', async (value: { book: book; shelf: string }) => {
    await update(value.book, value.shelf)
    // The value we return becomes the `fulfilled` action payload
    return { book: value.book, shelf: value.shelf }
})

export const searchBook = createAsyncThunk('book/searchBook', async (query: string, thunk) => {
    const { getState } = thunk
    // func takes id and return shelf if book added already else returns none
    const getShelf = (id: string) => {
        const x: any = getState()
        const book: book = x.books.value.find((book: book) => book.id === id)
        return book ? book.shelf : 'none'
    }

    if (query) {
        const response = await search(query, 10)
        // The value we return becomes the `fulfilled` action payload
        // adding shelf to each book
        const responseWithShelf = response.map((book: book) => ({ ...book, shelf: getShelf(book.id) }))
        return responseWithShelf
    } else {
        return []
    }
})

export const bookSlice = createSlice({
    name: 'book',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            // ***********
            // get all
            // ***********
            .addCase(getAllBooks.pending, (state) => {
                state.loading = true
                state.error = false
            })
            .addCase(getAllBooks.fulfilled, (state, action) => {
                state.loading = false
                state.error = false
                state.value = action.payload
            })
            .addCase(getAllBooks.rejected, (state) => {
                state.error = true
                state.loading = false
            })
            // ***********
            // update book
            // ***********
            .addCase(updateBook.pending, (state) => {
                state.loading = true
                state.error = false
            })
            .addCase(updateBook.fulfilled, (state, action) => {
                state.loading = false
                state.error = false
                const book = state.value.find((book: book) => book.id === action.payload.book.id)
                if (book) {
                    state.value = state.value.map((book) =>
                        book.id === action.payload.book.id ? { ...book, shelf: action.payload.shelf } : book
                    )
                } else {
                    state.value = [...state.value, { ...action.payload.book, shelf: action.payload.shelf }]
                }

                state.searchBooks = state.searchBooks.map((book: book) =>
                    book.id === action.payload.book.id ? { ...book, shelf: action.payload.shelf } : book
                )
            })
            .addCase(updateBook.rejected, (state) => {
                state.error = true
                state.loading = false
            })
            // ***********
            // search book
            // ***********
            .addCase(searchBook.pending, (state) => {
                state.loading = true
                state.error = false
            })
            .addCase(searchBook.fulfilled, (state, action) => {
                state.loading = false
                state.error = false
                if (!action.payload.error) {
                    state.searchBooks = action.payload
                } else {
                    state.searchBooks = []
                }
            })
            .addCase(searchBook.rejected, (state) => {
                state.error = true
                state.loading = false
            })
    }
})

// export const { increment, decrement, incrementByAmount } = bookSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

export const booksState = (state: RootState) => state.books

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default bookSlice.reducer
